### ISSUE TITLE
`yarn start` Error: Cannot find module '../../data'

### ISSUE THREAD

**Issue by gwpantazes** [skidding/jobs-done#12]
I tried installing the project locally and got an error on `yarn start`.

After git cloning the repository, I ran the following steps ([see the log in this gist](https://gist.github.com/gwpantazes/5284fc64d81ec112da59054a92197241))
1. `yarn install` installs seemingly fine (some benign warnings?)
2. `yarn start` error occurs

```
$ yarn start
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module '../../data'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/georgep/Documents/GitHub/jobs-done/components/App/Routes.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Module._compile (/Users/georgep/Documents/GitHub/jobs-done/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Object.newLoader [as .js] (/Users/georgep/Documents/GitHub/jobs-done/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:605:32)
error Command failed with exit code 1.
```

Environment: 
- yarn v1.12.1
- MacOS 10.13.6 (17G65)

**Comment by skidding** [comment]
See https://github.com/skidding/jobs-done/blob/master/README.md#how-to-use

**Comment by gwpantazes** [comment]
I followed the readme exactly.

**Comment by skidding** [comment]
@gwpantazes Did you get a chance to try again?

**Comment by gwpantazes** [comment]
Copying data.js to project root fixed it. Maybe data.js should be included from the start with some sensible defaults and the user can just modify that.
In any case, the updated instructions are good. Thank you @skidding
