### ISSUE TITLE
Calling 'yarn start' causes 'Error: Cannot find module 'Stylesheet'

### ISSUE THREAD

**Issue by Trozzza** [skidding/jobs-done#15]
I see this is similar to the other currently open issue https://github.com/skidding/jobs-done/issues/12 but I am getting an error for finding the stylesheet.

I was able to successfully do ```yarn install``` minus some warnings which I think are expected but stumped on what to do with this problem.

```
# yarn start
yarn run v1.12.1
$ NODE_ENV=development babel-node tools/start.js --config-file ./.babelrc.js --only '*.js,components/**,tools/**,node_modules/styled-components/**'
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'StyleSheet'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.get StyleSheet [as StyleSheet] (C:\Dev\jobs-done\node_modules\react-native\Libraries\react-native\react-native-implementation.js:96:29)
    at Object.<anonymous> (C:\Dev\jobs-done\node_modules\styled-components\dist\styled-components.native.cjs.js:5522:44)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (C:\Dev\jobs-done\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (C:\Dev\jobs-done\node_modules\pirates\lib\index.js:88:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by skidding** [comment]
@Timothee What machine are you on? Windows by any chance?

**Comment by skidding** [comment]
I pushed a commit that might fix your issue https://github.com/skidding/jobs-done/commit/4b12375d30ca05c9e2266697143246a2ea5baebc. Can you please get latest master and try again?

**Comment by Trozzza** [comment]
You're amazing, thank you so much for fixing this! I was super keen at work all day to try this out for myself.

I saw you also did this commit https://github.com/skidding/jobs-done/commit/8e149f6925846849b421139ee70ce3080f4141a1 which fixes another issue I had earlier but was able to fix myself.

I came across this Stackoverflow post https://stackoverflow.com/a/40967643/7788355 where someone wrote a module where you install it once and never have to worry about needing to put ```cross-env``` in front of ```NODE_ENV=...``` for it to work on Windows. Sharing in case interested 👍 

Please feel free to close this issue as it has been fixed!

**Comment by skidding** [comment]
> You're amazing, thank you so much for fixing this! I was super keen at work all day to try this out for myself.

❤️

> I came across this Stackoverflow post https://stackoverflow.com/a/40967643/7788355 where someone wrote a module where you install it once and never have to worry about needing to put cross-env in front of NODE_ENV=... for it to work on Windows. Sharing in case interested 👍

Good to know!
